services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=P@ssw0rd#_1234
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - logging
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - logging
    depends_on:
      - opensearch
  logstash:
    image: logstash
    build: ./logstash
    environment:
      - OPENSEARCH_HOST=https://opensearch:9200
      - OPENSEARCH_USER=app_logstash
      - OPENSEARCH_PASSWORD=AppLogstash#1234
    ports:
      - 5044:5044
    networks:
      - logging
volumes:
  opensearch-data:
networks:
  logging:
